runtime: python
env: flex
threadsafe: true
entrypoint: gunicorn -b :$PORT main:app
handlers:
- url: ../dist
  static_dir: static
- url: /.*
  script: auto

runtime_config:
    python_version: 3

env_variables:
    CLOUD_STORAGE_BUCKET: league-of-mentoring
